### PR TITLE
Finishing settings menu (except for mouse sens)

### PR DESCRIPTION
**Pull request by Bmoel**
- You can now change brightness of the main menu scene
- You can add bloom to scene (work in progress, need to add to specific nodes instead of whole screen)
- Master Volume, Music Volume, and SFX volume now functional
- Changed popup method of settings menu to ratio version, works a lot better with centering to screen
- Added two new audio busses to work with master volume (music and sfx, tutorial in discord)

### CODE REVIEW

**Review by FreemanSpray — APPROVED** [review]
Don’t see any potential problems looking at the changes. Does the warning-ignore in sceneTrans need to be uncommented or no?

**Comment by Bmoel** [comment]
> Don’t see any potential problems looking at the changes. Does the warning-ignore in sceneTrans need to be uncommented or no?

It should stay since it just removes warnings that popup from that function. It gives warnings since it returns a value that doesn't get used, but that comment makes the warning not happen

**Review by jsonFile01 — CHANGES_REQUESTED** [review]
Reminder: Add the viewport thing Mohit did for his fire animation.

**Review by jsonFile01 — APPROVED** [review]
Nice

**Review by rwyndrum4 — APPROVED** [review]

**Pull request merged**
