### PR TITLE
Player movement restrictions and player organization

### PR DESCRIPTION
**Pull request by Bmoel**
-made it so player can't move when textbox is being shown 
-did this by sending a signal from the textbox to the player script 
-I also changed the players inside of startArea and EntrySpace to be derived from the same base player 
-The player inside of EntrySpace just has a 2d camera added to it 
-This is to just help with not having to copy and paste the base player assets into each scene 
-now you can just instance it in
-also fixed an issue where the settings menu process function was running even when hidden

### CODE REVIEW

**Comment by Bmoel** [comment]
oh and I also added a new folder to hold all the minigame scenes and placed an empty scene for our riddle game. The timer also moves to that scene when it hits 0 now. For debugging too, I made it so if you press "P" the timer will reduce so you can quickly get to the minigame

**Comment by FreemanSpray** [comment]
All looks good! I love the timer debugging feature. It might be useful in the future (when we're testing the main map) to implement a key that can set the timer to some arbitrarily high number as well.

**Comment by FreemanSpray** [comment]
One thing I do notice after doing some further work on the minigame setup is that it looks like there's a slight bug with the Exit Cave text. It appears by default when the scene loads, and does not go away until the player enters the zone for the first time then exits it again. This is probably partly a consequence of my suboptimal fix for this text that I did previously.

**Comment by Bmoel** [comment]
> One thing I do notice after doing some further work on the minigame setup is that it looks like there's a slight bug with the Exit Cave text. It appears by default when the scene loads, and does not go away until the player enters the zone for the first time then exits it again. This is probably partly a consequence of my suboptimal fix for this text that I did previously.

Fixed this with the latest push, was due to layers and masks for the players, walls, and oval sensor being off
In the previous version, the player, walls, and oval were sharing the same layers and mask so the oval was detecting the wall colliders and ended up showing the instructions
Good explanation on how they work: https://godotengine.org/qa/4010/whats-difference-between-collision-layers-collision-masks
Here is how it works in our current scene:
-Players is layer 1, mask 1
-Wall colliders are layer 2, mask 1
-Oval sensor is layer 3, mask 1
-This means that the wall colliders and oval are ONLY detecting the player, and not each other

**Pull request merged**
