### PR TITLE
adding fps counter functionality

### PR DESCRIPTION
**Pull request by Bmoel**
Features:
- got rid of bloom parameter in the settings (not needed for our game)
- added FPS counter
    - Constitutes as a label in the main menu (can add it to game scene once we make it)
    - Can be turned on and off in the settings

### CODE REVIEW

**Comment by jsonFile01** [comment]
Its good. Just fixed fps display bug.

**Comment by FreemanSpray** [comment]
I noticed that after closing the first instance of the game and opening it again, I was no longer able to get fps values higher than 60 no matter what I changed the max to. I was still able to set the max to < 60, but any value > 60 would just cause the fps to cap at 60. Is anyone else able to reproduce this, or is it maybe my computer limiting the fps somehow?

**Comment by Bmoel** [comment]
> 
I couldn't replicate it, was the vsync option on as well? That could be forcing the frames to stay at the max for your screen, if not then I have no clue

**Comment by jsonFile01** [comment]
I too can't replicate this. What steps did you do to get this? My only issue is that vsync isn't working if it is suppose to work right now.

**Comment by Bmoel** [comment]
> I too can't replicate this. What steps did you do to get this? My only issue is that vsync isn't working if it is suppose to work right now.

Vsync was working for me yeah, didn't test it too extensively though

**Pull request merged**
